//! This module defines configurations, data structures, and utilities for managing client messages,
//! generating random names, and establishing socket-based communication in a Go Fish web application.
use std::collections::HashSet;
use go_fish_web::ClientMessage;
use serde::Deserialize;
use std::net::SocketAddr;
use rand::RngExt;
use rand::rngs::SmallRng;
use tracing::error;

#[derive(Debug)]
pub struct AddressedClientMessage {
    pub client: SocketAddr,
    pub client_message: ClientMessage,
}

#[derive(Debug, Deserialize)]
pub struct Config {
    pub address: SocketAddr,
    pub player_count: usize,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            address: SocketAddr::from(([127, 0, 0, 1], 9001)),
            player_count: 2,
        }
    }
}

/// A struct that provides functionality for generating and managing random names.
///
/// # Fields
///
/// * `random_names` - A `HashSet` that stores initially generated names.
/// * `available_names` - A `Vec` that contains a list of unique names available for players to take.
/// * `rng` - A private random number generator instance (`rand::rngs::ThreadRng`) used to randomly select names.
///
/// # Example
///
/// ```
/// use your_crate::RandomNameGenerator;
/// use std::collections::HashSet;
///
/// let available_names = vec!["Alice".to_string(), "Bob".to_string(), "Charlie".to_string()];
/// let mut generator = RandomNameGenerator {
///     random_names: HashSet::new(),
///     available_names,
///     rng: rand::thread_rng(),
/// };
///
/// // Generate and work with random names
/// ```
pub struct RandomNameGenerator {
    pub random_names: HashSet<String>,
    pub available_names: Vec<String>,
    rng: rand::rngs::SmallRng,
}

impl Default for RandomNameGenerator {
    fn default() -> Self {
        Self::new(Self::fish_names())
    }
}

impl RandomNameGenerator {
    /// Creates a new instance of `RandomNameGenerator`.
    ///
    /// # Arguments
    ///
    /// * `names` - A `HashSet` of `String`s representing the pool of names to use for the generator.
    ///
    /// # Returns
    ///
    /// A new `RandomNameGenerator` struct initialized with a pool of random names.
    ///
    /// # Example
    ///
    /// ```rust
    /// use std::collections::HashSet;
    /// let names: HashSet<String> = ["Alice", "Bob", "Charlie"].iter().map(|&s| s.into()).collect();
    /// let generator = RandomNameGenerator::new(names);
    /// ```
    pub fn new(names: HashSet<String>) -> Self {
        let random_names = names;
        let available_names = random_names.clone().into_iter().collect::<Vec<_>>();
        let rng: SmallRng = rand::make_rng();
        RandomNameGenerator {
            random_names,
            available_names,
            rng
        }
    }

    /// Retrieves a name from the list of available names and removes it.
    ///
    /// This method selects a random name from the internal list of `available_names` using a random
    /// index generated by the `rng` field. The selected name is removed from the list and returned
    /// as a `String`.
    ///
    /// # Returns
    /// - A `String` representing the randomly selected and removed name from `available_names`.
    ///
    /// # Panics
    /// - Panics if the `available_names` list is empty.
    ///
    /// # Example
    /// ```
    /// let mut manager = NameManager::new(vec!["Alice".to_string(), "Bob".to_string()]);
    /// let name = manager.get();
    /// println!("Retrieved name: {}", name);
    /// ```
    pub fn get(&mut self) -> String {
        if self.available_names.is_empty() {
            error!("No available names");
            panic!("No available names");
        }

        let r = self.rng.random_range(0..self.available_names.len());
        self.available_names.swap_remove(r)
    }

    fn fish_names() -> HashSet<String> {
        HashSet::from_iter(vec![
            "Angelfish",
            "Barracuda",
            "Blobfish",
            "Bass",
            "Clownfish",
            "Catfish",
            "Carp",
            "Cod",
            "Dogfish",
            "Eel",
            "Flounder",
            "Goldfish",
            "Grouper",
            "Guppy",
            "Lionfish",
            "Mackerel",
            "Minnow",
            "Mudskipper",
            "Needlefish",
            "Oarfish",
            "Parrotfish",
            "Pike",
            "Piranha",
            "Pufferfish",
            "Salmon",
            "Sardine",
            "Sturgeon",
            "Trout",
            "Tuna"
        ].iter().map(|s| s.to_string()))
    }
}